language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit